services:
  accounts:
    image: "tientran1504/accounts:v1"
    container_name: "accounts-ms"
    ports:
        - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700M
    networks:
    - "tdtien"
  loans:
    image: "tientran1504/loans:v1"
    container_name: "loans-ms"
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700M
    networks:
    - "tdtien"
  cards:
    image: "tientran1504/cards:v1"
    container_name: "cards-ms"
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 700M
    networks:
    - "tdtien"
networks:
  tdtien:
    driver: "bridge"
