accounts:
  message: "Welcome to accounts related local APIs "
  contactDetails:
    name: "John Doe - Developer"
    email: "{cipher}c856b1003ebb9602fa6afdaa12b9e659c4e6f355df54aa93ea1bb8223aff5041"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345