build:
  version: 1.0.2

accounts:
  message: "Welcome to accounts related localss APIs "
  contactDetails:
    name: "John Doe - Developer"
    email: "{cipher}c856b1003ebb9602fa6afdaa12b9e659c4e6f355df54aa93ea1bb8223aff5041"
  onCallSupport:
    - (666) 555-1234
    - (666) 523-1345