cards:
  message: "Welcome to EazyBank cards related QA APIs "
  contactDetails:
    name: "Cherryl Pankaj - QA Lead"
    email: "{cipher}c856b1003ebb9602fa6afdaa12b9e659c4e6f355df54aa93ea1bb8223aff5041"
  onCallSupport:
    - (310) 875-4367
    - (201) 236-1267