build:
  version: 1.0.1

loans:
  message: "Welcome to EazyBank loans related QA APIs "
  contactDetails:
    name: "Cyrano Marita - QA Lead"
    email: "{cipher}c856b1003ebb9602fa6afdaa12b9e659c4e6f355df54aa93ea1bb8223aff5041"
  onCallSupport:
    - (785) 545-6565
    - (853) 546-3467