build:
  version: 1.0.2

loans:
  message: "Welcome to EazyBank loans related prod APIs "
  contactDetails:
    name: "Pelias Sudhir - Product Owner"
    email: "{cipher}c856b1003ebb9602fa6afdaa12b9e659c4e6f355df54aa93ea1bb8223aff5041"
  onCallSupport:
    - (723) 656-8709
    - (156) 342-0956