loans:
  message: "Welcome to EazyBank loans related local APIs "
  contactDetails:
    name: "Amaal Grega - Developer"
    email: "{cipher}c856b1003ebb9602fa6afdaa12b9e659c4e6f355df54aa93ea1bb8223aff5041"
  onCallSupport:
    - (452) 456-2176
    - (546) 764-8934
