spring:
  config:
    activate:
      on-profile: qa

build:
  version: 1.0.1

accounts:
  message: "Welcome to accounts related local APIs "
  contactDetails:
    name: "John Doe - Developer"
    email: "john@mail.com"
  onCallSupport:
    - (777) 555-1234
    - (777) 523-1345