spring:
  config:
    activate:
      on-profile: prod
build:
  version: 1.0.2

accounts:
  message: "Welcome to accounts related local APIs "
  contactDetails:
    name: "John Doe - Developer"
    email: "john@mail.com"
  onCallSupport:
    - (666) 555-1234
    - (666) 523-1345