server:
    port: 8071
spring:
  application:
    name: configserver
  profiles:
    active: native
    #active: git
  cloud:
    config:
      server:
        native:
          search-locations: "classpath:/config"
         # search-locations: "file:///D://project//microservices//configs"
#        git:
#          uri: https://github.com/eazybytes/eazybytes-config.git
#          default-label: main
#          timeout: 5
#          clone-on-start: true
#          force-pull: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

encrypt:
  key: "s3cr3tK3y1234567"