server:
  port: 9090

spring:
  application:
    name: "message"
  cloud:
    function:
      definition: email|sms
    stream:
      bindings:
        emailsms-in-0: # the name of the input channel.
          destination: send-communication # the name of the input channel.
          group: ${spring.application.name}
        emailsms-out-0: # the name of the output channel.
          destination: communication-sent # the name of the output channel.
      kafka:
        binder:
          brokers:
            - localhost:9092
